name: Final Project Jayjay

on:
  pull_request:
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: setup gradle
      run: chmod +x gradlew
      
    - name: Run API Tests
      run: ./gradlew clean executeAPITests

    - name: Run Web UI Tests
      run: ./gradlew clean executeWebTests

    - name: Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: cucumber-reports
          path: |
            reports/api/api-cucumber-report.html
            reports/web/web-cucumber-report.html
